version: '3.9'

services:
  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    container_name: journai-client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    depends_on:
      - server

  server:
    build:
      context: ./server
    container_name: journai-backend
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: journai-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./server/.env

volumes:
  pgdata:
