spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/journai_db}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Logging configuration for production
logging:
  level:
    com.journai: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
