apiVersion: v1
kind: Service
metadata:
  name: journai-client-service
  namespace: journai
  labels:
    app: journai-client
spec:
  selector:
    app: journai-client
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
