apiVersion: v1
kind: Secret
metadata:
  name: journai-db-secrets
  namespace: journai
type: Opaque
data:
  POSTGRES_DB: am91cm5BSQ==
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9qb3VybmFp
